volumes:
  grafana_data:
    driver: local

services:
  rq_exporter:
    build: .
    image: jcoelho93/rq-exporter:latest
    # You can also configure the exporter using command line options
    # command: --redis-host redis --redis-pass 123456
    ports:
      - target: 9726
        published: 9726
        protocol: tcp
        mode: host
    environment:
      RQ_REDIS_HOST: 'redis'
      RQ_REDIS_PASS: '123456'
      RQ_EXPORTER_LOG_LEVEL: 'DEBUG'
    volumes:
      # Mount the package for development
      - type: bind
        source: ./rq_exporter
        target: /app/rq_exporter
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9726/metrics')"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.4-alpine
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    command:
      - redis-server
      - --bind 0.0.0.0
      - --requirepass 123456
      - --loglevel notice
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 30s

  # RQ workers
  # To run multiple replicas use:
  # docker compose --compatibility up
  worker:
    image: mdawar/rq-exporter:latest
    entrypoint: []
    command: rq worker high default low --url redis://:123456@redis:6379/0
    working_dir: /home/worker
    volumes:
      # Mount a sample project
      - type: bind
        source: ./compose/project
        target: /home/worker
    depends_on:
      - redis
      - rq_exporter
    deploy:
      replicas: 2

  # Enqueue jobs for testing
  enqueue:
    image: mdawar/rq-exporter:latest
    entrypoint: []
    command: python -u enqueue.py
    environment:
      RQ_REDIS_HOST: 'redis'
      RQ_REDIS_PASS: '123456'
    working_dir: /home/enqueue
    volumes:
      # Mount a sample project
      - type: bind
        source: ./compose/project
        target: /home/enqueue
    depends_on:
      - redis
      - rq_exporter

  # RQ dashboard
  # https://github.com/Parallels/rq-dashboard
  dashboard:
    image: eoranged/rq-dashboard
    command: -u redis://:123456@redis:6379/0
    ports:
      - target: 9181
        published: 9181
        protocol: tcp
        mode: host
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    volumes:
      # Prometheus config file
      - type: bind
        source: ./compose/prometheus.yml
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:11.3.1
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      # Grafana datasources
      # https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
      - type: bind
        source: ./compose/grafana-datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      # Grafana dashboards config
      # https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
      - type: bind
        source: ./compose/grafana-dashboards.yml
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
      # # RQ dashboard
      - type: bind
        source: ./grafana/rq-dashboard.json
        target: /etc/grafana/dashboards/rq-dashboard.json
      # Grafana data
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
