name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rq-exporter
          docker build . \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.ref_name }}

      - name: Run the tests
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rq-exporter
          docker run --rm --entrypoint python $IMAGE_NAME:latest -m unittest

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rq-exporter
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.ref_name }}
